//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Datos.Modelo.PEC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Med.Comun.Datos.Core;
    using Logistica.Dominio.Entidades;
    
    public partial class PECDbContext : DbContext, IDbContext
    {
        public PECDbContext(string nameOrConnectionString)
            : base(nameOrConnectionString)
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual IDbSet<Logistica.Dominio.Entidades.Agencias> Agencias { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.Areas> Areas { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.Categoria> Categoria { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.Constante> Constante { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.OpeTpo> OpeTpo { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.Menu> Menu { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.MenuOpciones> MenuOpciones { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.MenuOpcionRol> MenuOpcionRol { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.Opciones> Opciones { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.Roles> Roles { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.RHcargos> RHcargos { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.rrhh> rrhh { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.RHCargosPersona> RHCargosPersona { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.RolCargo> RolCargo { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.Producto> Producto { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.ProductoDetalle> ProductoDetalle { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.SubAlamacen> SubAlamacen { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.LogDevolucion> LogDevolucion { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.MovBS> MovBS { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.Mov> Mov { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.MovCta> MovCta { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.DetalleProceso> DetalleProceso { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.Proceso> Proceso { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.Persona> Persona { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.PersonaDireccion> PersonaDireccion { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.BienesServicios> BienesServicios { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.BSSaldos> BSSaldos { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.BSSerie> BSSerie { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.CodigoBarra> CodigoBarra { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.ConstSistema> ConstSistema { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.CtaBS> CtaBS { get; set; }
        public virtual IDbSet<Logistica.Dominio.Entidades.MovBSSerie> MovBSSerie { get; set; }
    }
}
