//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienesServicios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BienesServicios()
        {
            this.BSSaldos = new HashSet<BSSaldos>();
        }
    
        public System.Guid idBS { get; set; }
        public string cBSCod { get; set; }
        public Nullable<int> nBSUnidad { get; set; }
        public string cBSDescripcion { get; set; }
        public Nullable<bool> bSerie { get; set; }
        public Nullable<bool> bVerifica { get; set; }
        public Nullable<bool> bContiene { get; set; }
        public Nullable<bool> bVigente { get; set; }
        public Nullable<bool> bCorrela { get; set; }
        public Nullable<int> nPorDeprecia { get; set; }
        public string cUltimaActualizacion { get; set; }
        public Nullable<int> nBSTipDep { get; set; }
        public Nullable<int> nStockMinimo { get; set; }
        public Nullable<bool> bPromocion { get; set; }
        public string Producto { get; set; }
        public string TipProducto { get; set; }
        public string Modelo { get; set; }
        public string Disenio { get; set; }
        public string Color { get; set; }
        public string usuario { get; set; }
        public string agencia { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BSSaldos> BSSaldos { get; set; }
    }
}
