//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSSerie
    {
        public System.Guid idBSCod { get; set; }
        public System.Guid idSerie { get; set; }
        public Nullable<int> nBienEstado { get; set; }
        public Nullable<decimal> nIGV { get; set; }
        public Nullable<decimal> nValor { get; set; }
    
        public virtual MovBSSerie MovBSSerie { get; set; }
    }
}
