//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public System.Guid idCategoria { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdCategoriaSuperior { get; set; }
        public Nullable<bool> esPrincipal { get; set; }
        public string Filtro { get; set; }
        public Nullable<int> Codigo { get; set; }
    }
}
