//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constante
    {
        public System.Guid idCons { get; set; }
        public Nullable<int> nConsValor { get; set; }
        public Nullable<int> nConsCod { get; set; }
        public string cConsDescripcion { get; set; }
    }
}
