//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstSistema
    {
        public System.Guid idConsSis { get; set; }
        public int nConsSisCod { get; set; }
        public int nConsSisValor { get; set; }
        public System.DateTime dFecIngreso { get; set; }
        public string cUser { get; set; }
    }
}
