//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtaBS
    {
        public System.Guid idBSCta { get; set; }
        public string cCtaContCod { get; set; }
        public Nullable<int> nCtaObjOrden { get; set; }
        public string cObjetoCod { get; set; }
        public string cOpeCod { get; set; }
        public Nullable<int> nCtaObjNiv { get; set; }
        public string cCtaObjFiltro { get; set; }
        public string cCtaObjImpre { get; set; }
        public string cCtaObjOpc { get; set; }
    }
}
