//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleProceso
    {
        public System.Guid idDetProceso { get; set; }
        public System.Guid IdProceso { get; set; }
        public Nullable<int> NMovCantAtend { get; set; }
        public Nullable<System.Guid> idBS { get; set; }
        public string CBSDescripcion { get; set; }
        public Nullable<int> NMovObjOrden { get; set; }
        public string CObjetoCod { get; set; }
        public string CCtaContCodD { get; set; }
        public string CCtaContCod { get; set; }
        public Nullable<int> NMovItem { get; set; }
        public Nullable<int> NMovImporte { get; set; }
        public Nullable<int> NIGV { get; set; }
        public Nullable<int> NIGVUnit { get; set; }
        public Nullable<int> NMovCant { get; set; }
        public Nullable<int> NValor { get; set; }
        public Nullable<int> NValorUnit { get; set; }
        public string OtroVariable { get; set; }
        public string OtroTexto { get; set; }
        public string Estado { get; set; }
        public string EstadoValue { get; set; }
    
        public virtual Proceso Proceso { get; set; }
    }
}
