//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogDevolucion
    {
        public System.Guid idDevol { get; set; }
        public Nullable<System.Guid> idMov { get; set; }
        public Nullable<System.Guid> idBS { get; set; }
        public string area { get; set; }
        public string medida { get; set; }
        public string serie { get; set; }
        public string situacion { get; set; }
        public string otro { get; set; }
        public string placa { get; set; }
    
        public virtual Mov Mov { get; set; }
    }
}
