//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuOpciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuOpciones()
        {
            this.MenuOpcionRol = new HashSet<MenuOpcionRol>();
        }
    
        public Nullable<System.Guid> idMenu { get; set; }
        public Nullable<System.Guid> idOpcion { get; set; }
        public int idMenuOpcion { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Opciones Opciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuOpcionRol> MenuOpcionRol { get; set; }
    }
}
