//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuOpcionRol
    {
        public int idMenuOpcionRol { get; set; }
        public System.Guid idRol { get; set; }
        public int idMenuOpcion { get; set; }
        public bool bEstado { get; set; }
        public System.DateTime dFecIngreso { get; set; }
        public Nullable<System.DateTime> dFecMod { get; set; }
        public string cUsu { get; set; }
    
        public virtual MenuOpciones MenuOpciones { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
