//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mov
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mov()
        {
            this.LogDevolucion = new HashSet<LogDevolucion>();
            this.ProductoDetalle = new HashSet<ProductoDetalle>();
        }
    
        public System.Guid idMov { get; set; }
        public int nMovNro { get; set; }
        public Nullable<int> nMovEstado { get; set; }
        public Nullable<int> nMovFlag { get; set; }
        public Nullable<System.Guid> cOpeCod { get; set; }
        public string cCodUsu { get; set; }
        public string cMovDesc { get; set; }
        public Nullable<System.DateTime> dFecMov { get; set; }
        public Nullable<System.TimeSpan> thoramov { get; set; }
        public string cCodAge { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogDevolucion> LogDevolucion { get; set; }
        public virtual OpeTpo OpeTpo { get; set; }
        public virtual MovBS MovBS { get; set; }
        public virtual MovCta MovCta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoDetalle> ProductoDetalle { get; set; }
    }
}
