//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovBSSerie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovBSSerie()
        {
            this.BSSerie = new HashSet<BSSerie>();
        }
    
        public System.Guid idSerie { get; set; }
        public Nullable<System.Guid> idMov { get; set; }
        public Nullable<int> nMovItem { get; set; }
        public string cBSCod { get; set; }
        public string cSerie { get; set; }
        public Nullable<int> nIgv { get; set; }
        public Nullable<decimal> nValor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BSSerie> BSSerie { get; set; }
    }
}
