//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Opciones()
        {
            this.MenuOpciones = new HashSet<MenuOpciones>();
        }
    
        public System.Guid idOpcion { get; set; }
        public string cOpcion { get; set; }
        public bool bEstado { get; set; }
        public System.DateTime dFecIngreso { get; set; }
        public Nullable<System.DateTime> dFecMod { get; set; }
        public string cUsu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuOpciones> MenuOpciones { get; set; }
    }
}
