//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaDireccion
    {
        public System.Guid idPersona { get; set; }
        public string cPersDireccion1 { get; set; }
        public string cPersDireccion2 { get; set; }
        public string cPersDireccion3 { get; set; }
        public string cPersDireccion4 { get; set; }
        public string cPersDireccion5 { get; set; }
        public System.DateTime dFecIngreso { get; set; }
        public Nullable<System.DateTime> dFecMod { get; set; }
        public string cUsu { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
