//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proceso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proceso()
        {
            this.DetalleProceso = new HashSet<DetalleProceso>();
        }
    
        public System.Guid idProceso { get; set; }
        public string cPersCod { get; set; }
        public string cPersNombre { get; set; }
        public string cUser { get; set; }
        public string cAgeCod { get; set; }
        public string cAreaCod { get; set; }
        public string subAlmacen { get; set; }
        public Nullable<int> idSubAlmacen { get; set; }
        public Nullable<int> pnMovEstado { get; set; }
        public Nullable<int> nMovEstadoRef { get; set; }
        public Nullable<int> nMovFlagRef { get; set; }
        public Nullable<int> nMovFlag { get; set; }
        public Nullable<int> nMovNro { get; set; }
        public string psMovNro { get; set; }
        public Nullable<int> nDocTpo { get; set; }
        public string cDocNro { get; set; }
        public string pcOpeCod { get; set; }
        public string comentario { get; set; }
        public Nullable<int> idAlmacen { get; set; }
        public Nullable<int> movRef { get; set; }
        public string otroDescripcion { get; set; }
        public string otroItem { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public string accion { get; set; }
        public Nullable<System.DateTime> fechaEmision { get; set; }
        public Nullable<System.DateTime> fechaEntrega { get; set; }
        public Nullable<System.DateTime> fechaSalida { get; set; }
        public string almacen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleProceso> DetalleProceso { get; set; }
    }
}
