//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoDetalle
    {
        public int nProductoDet { get; set; }
        public System.Guid idProducto { get; set; }
        public Nullable<System.Guid> idMov { get; set; }
        public Nullable<int> nMovNroSal { get; set; }
        public Nullable<int> nMovTrans { get; set; }
        public Nullable<int> nMovNroCesion { get; set; }
        public Nullable<int> nMovNroBaja { get; set; }
        public string cBSCod { get; set; }
        public string serie { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<bool> vigente { get; set; }
        public Nullable<int> nAlmCod { get; set; }
        public string cAreaCod { get; set; }
        public string cAgeCod { get; set; }
        public Nullable<int> cPersCod { get; set; }
        public string cPersNombre { get; set; }
        public Nullable<System.Guid> idSubAlmacen { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual SubAlamacen SubAlamacen { get; set; }
        public virtual Mov Mov { get; set; }
    }
}
