//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolCargo
    {
        public System.Guid idRol { get; set; }
        public System.Guid idRHCargoCod { get; set; }
        public System.DateTime dRolCargoFec { get; set; }
        public Nullable<System.DateTime> dRolCargoFecMod { get; set; }
        public string cUsu { get; set; }
    
        public virtual RHcargos RHcargos { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
