//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rrhh()
        {
            this.RHCargosPersona = new HashSet<RHCargosPersona>();
        }
    
        public System.Guid idRHCod { get; set; }
        public Nullable<int> cPersCod { get; set; }
        public Nullable<int> nRHEstado { get; set; }
        public string cClave { get; set; }
        public string cUser { get; set; }
        public string cAreaCod { get; set; }
        public string cAreaCodActual { get; set; }
        public string cAgenciaActual { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RHCargosPersona> RHCargosPersona { get; set; }
    }
}
