//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubAlamacen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubAlamacen()
        {
            this.ProductoDetalle = new HashSet<ProductoDetalle>();
        }
    
        public string nombre { get; set; }
        public string ubicacion { get; set; }
        public string cAgeCod { get; set; }
        public System.Guid idSubAlmacen { get; set; }
    
        public virtual Agencias Agencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoDetalle> ProductoDetalle { get; set; }
    }
}
